spring:
  application:
    name: ticket-reservation
    version: 1.0
  profiles:
    active: local # [ local, dev, prod]
  # 베너 색상 추가
  output:
    ansi:
      enabled: ALWAYS

###############
# Micrometer #
###############
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus

###############
# snow-flake #
###############
snow-flake:
  datacenter-id: 1
  worker-id: 1

###############
# JWT        #
###############
jwt:
  secret: "your-very-long-secret-key-that-is-at-least-256-bits-long-for-hs256-algorithm"
  access-token-expiration: 3600000    # 1시간 (ms)
  refresh-token-expiration: 604800000 # 7일 (ms)

